[package]
name = "sha1cracker"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sha-1 = "0.9"
hex = "0.4"

[profile.release]
lto = true
codegen-units = 1
panic = 'abort'
opt-level = "z"
strip = true